<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>drone_bringup</name>
  <version>0.0.0</version>
  <description>Bringup launch files for the drone.</description>
  <maintainer email="havriutkin@gmail.com">Vladyslav Havriutkin</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>drone_gazebo</exec_depend>
  <exec_depend>drone_control</exec_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>